// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="polarFir_polarFir,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5146,HLS_SYN_LUT=9306,HLS_VERSION=2022_2}" *)

module polarFir (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        m_axi_imgIn_AWVALID,
        m_axi_imgIn_AWREADY,
        m_axi_imgIn_AWADDR,
        m_axi_imgIn_AWID,
        m_axi_imgIn_AWLEN,
        m_axi_imgIn_AWSIZE,
        m_axi_imgIn_AWBURST,
        m_axi_imgIn_AWLOCK,
        m_axi_imgIn_AWCACHE,
        m_axi_imgIn_AWPROT,
        m_axi_imgIn_AWQOS,
        m_axi_imgIn_AWREGION,
        m_axi_imgIn_AWUSER,
        m_axi_imgIn_WVALID,
        m_axi_imgIn_WREADY,
        m_axi_imgIn_WDATA,
        m_axi_imgIn_WSTRB,
        m_axi_imgIn_WLAST,
        m_axi_imgIn_WID,
        m_axi_imgIn_WUSER,
        m_axi_imgIn_ARVALID,
        m_axi_imgIn_ARREADY,
        m_axi_imgIn_ARADDR,
        m_axi_imgIn_ARID,
        m_axi_imgIn_ARLEN,
        m_axi_imgIn_ARSIZE,
        m_axi_imgIn_ARBURST,
        m_axi_imgIn_ARLOCK,
        m_axi_imgIn_ARCACHE,
        m_axi_imgIn_ARPROT,
        m_axi_imgIn_ARQOS,
        m_axi_imgIn_ARREGION,
        m_axi_imgIn_ARUSER,
        m_axi_imgIn_RVALID,
        m_axi_imgIn_RREADY,
        m_axi_imgIn_RDATA,
        m_axi_imgIn_RLAST,
        m_axi_imgIn_RID,
        m_axi_imgIn_RUSER,
        m_axi_imgIn_RRESP,
        m_axi_imgIn_BVALID,
        m_axi_imgIn_BREADY,
        m_axi_imgIn_BRESP,
        m_axi_imgIn_BID,
        m_axi_imgIn_BUSER,
        m_axi_realIn_AWVALID,
        m_axi_realIn_AWREADY,
        m_axi_realIn_AWADDR,
        m_axi_realIn_AWID,
        m_axi_realIn_AWLEN,
        m_axi_realIn_AWSIZE,
        m_axi_realIn_AWBURST,
        m_axi_realIn_AWLOCK,
        m_axi_realIn_AWCACHE,
        m_axi_realIn_AWPROT,
        m_axi_realIn_AWQOS,
        m_axi_realIn_AWREGION,
        m_axi_realIn_AWUSER,
        m_axi_realIn_WVALID,
        m_axi_realIn_WREADY,
        m_axi_realIn_WDATA,
        m_axi_realIn_WSTRB,
        m_axi_realIn_WLAST,
        m_axi_realIn_WID,
        m_axi_realIn_WUSER,
        m_axi_realIn_ARVALID,
        m_axi_realIn_ARREADY,
        m_axi_realIn_ARADDR,
        m_axi_realIn_ARID,
        m_axi_realIn_ARLEN,
        m_axi_realIn_ARSIZE,
        m_axi_realIn_ARBURST,
        m_axi_realIn_ARLOCK,
        m_axi_realIn_ARCACHE,
        m_axi_realIn_ARPROT,
        m_axi_realIn_ARQOS,
        m_axi_realIn_ARREGION,
        m_axi_realIn_ARUSER,
        m_axi_realIn_RVALID,
        m_axi_realIn_RREADY,
        m_axi_realIn_RDATA,
        m_axi_realIn_RLAST,
        m_axi_realIn_RID,
        m_axi_realIn_RUSER,
        m_axi_realIn_RRESP,
        m_axi_realIn_BVALID,
        m_axi_realIn_BREADY,
        m_axi_realIn_BRESP,
        m_axi_realIn_BID,
        m_axi_realIn_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_IMGIN_ID_WIDTH = 1;
parameter    C_M_AXI_IMGIN_ADDR_WIDTH = 64;
parameter    C_M_AXI_IMGIN_DATA_WIDTH = 32;
parameter    C_M_AXI_IMGIN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IMGIN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IMGIN_WUSER_WIDTH = 1;
parameter    C_M_AXI_IMGIN_RUSER_WIDTH = 1;
parameter    C_M_AXI_IMGIN_BUSER_WIDTH = 1;
parameter    C_M_AXI_IMGIN_USER_VALUE = 0;
parameter    C_M_AXI_IMGIN_PROT_VALUE = 0;
parameter    C_M_AXI_IMGIN_CACHE_VALUE = 3;
parameter    C_M_AXI_REALIN_ID_WIDTH = 1;
parameter    C_M_AXI_REALIN_ADDR_WIDTH = 64;
parameter    C_M_AXI_REALIN_DATA_WIDTH = 32;
parameter    C_M_AXI_REALIN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_REALIN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_REALIN_WUSER_WIDTH = 1;
parameter    C_M_AXI_REALIN_RUSER_WIDTH = 1;
parameter    C_M_AXI_REALIN_BUSER_WIDTH = 1;
parameter    C_M_AXI_REALIN_USER_VALUE = 0;
parameter    C_M_AXI_REALIN_PROT_VALUE = 0;
parameter    C_M_AXI_REALIN_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IMGIN_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_REALIN_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output   m_axi_imgIn_AWVALID;
input   m_axi_imgIn_AWREADY;
output  [C_M_AXI_IMGIN_ADDR_WIDTH - 1:0] m_axi_imgIn_AWADDR;
output  [C_M_AXI_IMGIN_ID_WIDTH - 1:0] m_axi_imgIn_AWID;
output  [7:0] m_axi_imgIn_AWLEN;
output  [2:0] m_axi_imgIn_AWSIZE;
output  [1:0] m_axi_imgIn_AWBURST;
output  [1:0] m_axi_imgIn_AWLOCK;
output  [3:0] m_axi_imgIn_AWCACHE;
output  [2:0] m_axi_imgIn_AWPROT;
output  [3:0] m_axi_imgIn_AWQOS;
output  [3:0] m_axi_imgIn_AWREGION;
output  [C_M_AXI_IMGIN_AWUSER_WIDTH - 1:0] m_axi_imgIn_AWUSER;
output   m_axi_imgIn_WVALID;
input   m_axi_imgIn_WREADY;
output  [C_M_AXI_IMGIN_DATA_WIDTH - 1:0] m_axi_imgIn_WDATA;
output  [C_M_AXI_IMGIN_WSTRB_WIDTH - 1:0] m_axi_imgIn_WSTRB;
output   m_axi_imgIn_WLAST;
output  [C_M_AXI_IMGIN_ID_WIDTH - 1:0] m_axi_imgIn_WID;
output  [C_M_AXI_IMGIN_WUSER_WIDTH - 1:0] m_axi_imgIn_WUSER;
output   m_axi_imgIn_ARVALID;
input   m_axi_imgIn_ARREADY;
output  [C_M_AXI_IMGIN_ADDR_WIDTH - 1:0] m_axi_imgIn_ARADDR;
output  [C_M_AXI_IMGIN_ID_WIDTH - 1:0] m_axi_imgIn_ARID;
output  [7:0] m_axi_imgIn_ARLEN;
output  [2:0] m_axi_imgIn_ARSIZE;
output  [1:0] m_axi_imgIn_ARBURST;
output  [1:0] m_axi_imgIn_ARLOCK;
output  [3:0] m_axi_imgIn_ARCACHE;
output  [2:0] m_axi_imgIn_ARPROT;
output  [3:0] m_axi_imgIn_ARQOS;
output  [3:0] m_axi_imgIn_ARREGION;
output  [C_M_AXI_IMGIN_ARUSER_WIDTH - 1:0] m_axi_imgIn_ARUSER;
input   m_axi_imgIn_RVALID;
output   m_axi_imgIn_RREADY;
input  [C_M_AXI_IMGIN_DATA_WIDTH - 1:0] m_axi_imgIn_RDATA;
input   m_axi_imgIn_RLAST;
input  [C_M_AXI_IMGIN_ID_WIDTH - 1:0] m_axi_imgIn_RID;
input  [C_M_AXI_IMGIN_RUSER_WIDTH - 1:0] m_axi_imgIn_RUSER;
input  [1:0] m_axi_imgIn_RRESP;
input   m_axi_imgIn_BVALID;
output   m_axi_imgIn_BREADY;
input  [1:0] m_axi_imgIn_BRESP;
input  [C_M_AXI_IMGIN_ID_WIDTH - 1:0] m_axi_imgIn_BID;
input  [C_M_AXI_IMGIN_BUSER_WIDTH - 1:0] m_axi_imgIn_BUSER;
output   m_axi_realIn_AWVALID;
input   m_axi_realIn_AWREADY;
output  [C_M_AXI_REALIN_ADDR_WIDTH - 1:0] m_axi_realIn_AWADDR;
output  [C_M_AXI_REALIN_ID_WIDTH - 1:0] m_axi_realIn_AWID;
output  [7:0] m_axi_realIn_AWLEN;
output  [2:0] m_axi_realIn_AWSIZE;
output  [1:0] m_axi_realIn_AWBURST;
output  [1:0] m_axi_realIn_AWLOCK;
output  [3:0] m_axi_realIn_AWCACHE;
output  [2:0] m_axi_realIn_AWPROT;
output  [3:0] m_axi_realIn_AWQOS;
output  [3:0] m_axi_realIn_AWREGION;
output  [C_M_AXI_REALIN_AWUSER_WIDTH - 1:0] m_axi_realIn_AWUSER;
output   m_axi_realIn_WVALID;
input   m_axi_realIn_WREADY;
output  [C_M_AXI_REALIN_DATA_WIDTH - 1:0] m_axi_realIn_WDATA;
output  [C_M_AXI_REALIN_WSTRB_WIDTH - 1:0] m_axi_realIn_WSTRB;
output   m_axi_realIn_WLAST;
output  [C_M_AXI_REALIN_ID_WIDTH - 1:0] m_axi_realIn_WID;
output  [C_M_AXI_REALIN_WUSER_WIDTH - 1:0] m_axi_realIn_WUSER;
output   m_axi_realIn_ARVALID;
input   m_axi_realIn_ARREADY;
output  [C_M_AXI_REALIN_ADDR_WIDTH - 1:0] m_axi_realIn_ARADDR;
output  [C_M_AXI_REALIN_ID_WIDTH - 1:0] m_axi_realIn_ARID;
output  [7:0] m_axi_realIn_ARLEN;
output  [2:0] m_axi_realIn_ARSIZE;
output  [1:0] m_axi_realIn_ARBURST;
output  [1:0] m_axi_realIn_ARLOCK;
output  [3:0] m_axi_realIn_ARCACHE;
output  [2:0] m_axi_realIn_ARPROT;
output  [3:0] m_axi_realIn_ARQOS;
output  [3:0] m_axi_realIn_ARREGION;
output  [C_M_AXI_REALIN_ARUSER_WIDTH - 1:0] m_axi_realIn_ARUSER;
input   m_axi_realIn_RVALID;
output   m_axi_realIn_RREADY;
input  [C_M_AXI_REALIN_DATA_WIDTH - 1:0] m_axi_realIn_RDATA;
input   m_axi_realIn_RLAST;
input  [C_M_AXI_REALIN_ID_WIDTH - 1:0] m_axi_realIn_RID;
input  [C_M_AXI_REALIN_RUSER_WIDTH - 1:0] m_axi_realIn_RUSER;
input  [1:0] m_axi_realIn_RRESP;
input   m_axi_realIn_BVALID;
output   m_axi_realIn_BREADY;
input  [1:0] m_axi_realIn_BRESP;
input  [C_M_AXI_REALIN_ID_WIDTH - 1:0] m_axi_realIn_BID;
input  [C_M_AXI_REALIN_BUSER_WIDTH - 1:0] m_axi_realIn_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] inputReal;
wire   [63:0] inputImg;
wire   [63:0] outputMag;
wire   [63:0] outputPhase;
wire   [31:0] inputLength;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem_AWREADY;
wire    gmem_WREADY;
wire    gmem_ARREADY;
wire    gmem_RVALID;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    imgIn_AWREADY;
wire    imgIn_WREADY;
wire    imgIn_ARREADY;
wire    imgIn_RVALID;
wire   [31:0] imgIn_RDATA;
wire    imgIn_RLAST;
wire   [0:0] imgIn_RID;
wire   [8:0] imgIn_RFIFONUM;
wire   [0:0] imgIn_RUSER;
wire   [1:0] imgIn_RRESP;
wire    imgIn_BVALID;
wire    realIn_AWREADY;
wire    realIn_WREADY;
wire    realIn_ARREADY;
wire    realIn_RVALID;
wire   [31:0] realIn_RDATA;
wire    realIn_RLAST;
wire   [0:0] realIn_RID;
wire   [8:0] realIn_RFIFONUM;
wire   [0:0] realIn_RUSER;
wire   [1:0] realIn_RRESP;
wire    realIn_BVALID;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_outputMag_c_din;
wire    entry_proc_U0_outputMag_c_write;
wire   [63:0] entry_proc_U0_outputPhase_c_din;
wire    entry_proc_U0_outputPhase_c_write;
wire    complexFIR_U0_ap_start;
wire    complexFIR_U0_ap_done;
wire    complexFIR_U0_ap_continue;
wire    complexFIR_U0_ap_idle;
wire    complexFIR_U0_ap_ready;
wire    complexFIR_U0_m_axi_realIn_AWVALID;
wire   [63:0] complexFIR_U0_m_axi_realIn_AWADDR;
wire   [0:0] complexFIR_U0_m_axi_realIn_AWID;
wire   [31:0] complexFIR_U0_m_axi_realIn_AWLEN;
wire   [2:0] complexFIR_U0_m_axi_realIn_AWSIZE;
wire   [1:0] complexFIR_U0_m_axi_realIn_AWBURST;
wire   [1:0] complexFIR_U0_m_axi_realIn_AWLOCK;
wire   [3:0] complexFIR_U0_m_axi_realIn_AWCACHE;
wire   [2:0] complexFIR_U0_m_axi_realIn_AWPROT;
wire   [3:0] complexFIR_U0_m_axi_realIn_AWQOS;
wire   [3:0] complexFIR_U0_m_axi_realIn_AWREGION;
wire   [0:0] complexFIR_U0_m_axi_realIn_AWUSER;
wire    complexFIR_U0_m_axi_realIn_WVALID;
wire   [31:0] complexFIR_U0_m_axi_realIn_WDATA;
wire   [3:0] complexFIR_U0_m_axi_realIn_WSTRB;
wire    complexFIR_U0_m_axi_realIn_WLAST;
wire   [0:0] complexFIR_U0_m_axi_realIn_WID;
wire   [0:0] complexFIR_U0_m_axi_realIn_WUSER;
wire    complexFIR_U0_m_axi_realIn_ARVALID;
wire   [63:0] complexFIR_U0_m_axi_realIn_ARADDR;
wire   [0:0] complexFIR_U0_m_axi_realIn_ARID;
wire   [31:0] complexFIR_U0_m_axi_realIn_ARLEN;
wire   [2:0] complexFIR_U0_m_axi_realIn_ARSIZE;
wire   [1:0] complexFIR_U0_m_axi_realIn_ARBURST;
wire   [1:0] complexFIR_U0_m_axi_realIn_ARLOCK;
wire   [3:0] complexFIR_U0_m_axi_realIn_ARCACHE;
wire   [2:0] complexFIR_U0_m_axi_realIn_ARPROT;
wire   [3:0] complexFIR_U0_m_axi_realIn_ARQOS;
wire   [3:0] complexFIR_U0_m_axi_realIn_ARREGION;
wire   [0:0] complexFIR_U0_m_axi_realIn_ARUSER;
wire    complexFIR_U0_m_axi_realIn_RREADY;
wire    complexFIR_U0_m_axi_realIn_BREADY;
wire    complexFIR_U0_m_axi_imgIn_AWVALID;
wire   [63:0] complexFIR_U0_m_axi_imgIn_AWADDR;
wire   [0:0] complexFIR_U0_m_axi_imgIn_AWID;
wire   [31:0] complexFIR_U0_m_axi_imgIn_AWLEN;
wire   [2:0] complexFIR_U0_m_axi_imgIn_AWSIZE;
wire   [1:0] complexFIR_U0_m_axi_imgIn_AWBURST;
wire   [1:0] complexFIR_U0_m_axi_imgIn_AWLOCK;
wire   [3:0] complexFIR_U0_m_axi_imgIn_AWCACHE;
wire   [2:0] complexFIR_U0_m_axi_imgIn_AWPROT;
wire   [3:0] complexFIR_U0_m_axi_imgIn_AWQOS;
wire   [3:0] complexFIR_U0_m_axi_imgIn_AWREGION;
wire   [0:0] complexFIR_U0_m_axi_imgIn_AWUSER;
wire    complexFIR_U0_m_axi_imgIn_WVALID;
wire   [31:0] complexFIR_U0_m_axi_imgIn_WDATA;
wire   [3:0] complexFIR_U0_m_axi_imgIn_WSTRB;
wire    complexFIR_U0_m_axi_imgIn_WLAST;
wire   [0:0] complexFIR_U0_m_axi_imgIn_WID;
wire   [0:0] complexFIR_U0_m_axi_imgIn_WUSER;
wire    complexFIR_U0_m_axi_imgIn_ARVALID;
wire   [63:0] complexFIR_U0_m_axi_imgIn_ARADDR;
wire   [0:0] complexFIR_U0_m_axi_imgIn_ARID;
wire   [31:0] complexFIR_U0_m_axi_imgIn_ARLEN;
wire   [2:0] complexFIR_U0_m_axi_imgIn_ARSIZE;
wire   [1:0] complexFIR_U0_m_axi_imgIn_ARBURST;
wire   [1:0] complexFIR_U0_m_axi_imgIn_ARLOCK;
wire   [3:0] complexFIR_U0_m_axi_imgIn_ARCACHE;
wire   [2:0] complexFIR_U0_m_axi_imgIn_ARPROT;
wire   [3:0] complexFIR_U0_m_axi_imgIn_ARQOS;
wire   [3:0] complexFIR_U0_m_axi_imgIn_ARREGION;
wire   [0:0] complexFIR_U0_m_axi_imgIn_ARUSER;
wire    complexFIR_U0_m_axi_imgIn_RREADY;
wire    complexFIR_U0_m_axi_imgIn_BREADY;
wire   [17:0] complexFIR_U0_realStream2_din;
wire    complexFIR_U0_realStream2_write;
wire   [17:0] complexFIR_U0_imgStream3_din;
wire    complexFIR_U0_imgStream3_write;
wire   [31:0] complexFIR_U0_inputLength_c_din;
wire    complexFIR_U0_inputLength_c_write;
wire    bulkCordicConvert_U0_ap_start;
wire    bulkCordicConvert_U0_ap_done;
wire    bulkCordicConvert_U0_ap_continue;
wire    bulkCordicConvert_U0_ap_idle;
wire    bulkCordicConvert_U0_ap_ready;
wire    bulkCordicConvert_U0_realStream2_read;
wire    bulkCordicConvert_U0_imgStream3_read;
wire    bulkCordicConvert_U0_m_axi_gmem_AWVALID;
wire   [63:0] bulkCordicConvert_U0_m_axi_gmem_AWADDR;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_AWID;
wire   [31:0] bulkCordicConvert_U0_m_axi_gmem_AWLEN;
wire   [2:0] bulkCordicConvert_U0_m_axi_gmem_AWSIZE;
wire   [1:0] bulkCordicConvert_U0_m_axi_gmem_AWBURST;
wire   [1:0] bulkCordicConvert_U0_m_axi_gmem_AWLOCK;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_AWCACHE;
wire   [2:0] bulkCordicConvert_U0_m_axi_gmem_AWPROT;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_AWQOS;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_AWREGION;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_AWUSER;
wire    bulkCordicConvert_U0_m_axi_gmem_WVALID;
wire   [31:0] bulkCordicConvert_U0_m_axi_gmem_WDATA;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_WSTRB;
wire    bulkCordicConvert_U0_m_axi_gmem_WLAST;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_WID;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_WUSER;
wire    bulkCordicConvert_U0_m_axi_gmem_ARVALID;
wire   [63:0] bulkCordicConvert_U0_m_axi_gmem_ARADDR;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_ARID;
wire   [31:0] bulkCordicConvert_U0_m_axi_gmem_ARLEN;
wire   [2:0] bulkCordicConvert_U0_m_axi_gmem_ARSIZE;
wire   [1:0] bulkCordicConvert_U0_m_axi_gmem_ARBURST;
wire   [1:0] bulkCordicConvert_U0_m_axi_gmem_ARLOCK;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_ARCACHE;
wire   [2:0] bulkCordicConvert_U0_m_axi_gmem_ARPROT;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_ARQOS;
wire   [3:0] bulkCordicConvert_U0_m_axi_gmem_ARREGION;
wire   [0:0] bulkCordicConvert_U0_m_axi_gmem_ARUSER;
wire    bulkCordicConvert_U0_m_axi_gmem_RREADY;
wire    bulkCordicConvert_U0_m_axi_gmem_BREADY;
wire    bulkCordicConvert_U0_mag_read;
wire    bulkCordicConvert_U0_theta_read;
wire    bulkCordicConvert_U0_convertSize_read;
wire    outputMag_c_full_n;
wire   [63:0] outputMag_c_dout;
wire   [2:0] outputMag_c_num_data_valid;
wire   [2:0] outputMag_c_fifo_cap;
wire    outputMag_c_empty_n;
wire    outputPhase_c_full_n;
wire   [63:0] outputPhase_c_dout;
wire   [2:0] outputPhase_c_num_data_valid;
wire   [2:0] outputPhase_c_fifo_cap;
wire    outputPhase_c_empty_n;
wire    realStream_full_n;
wire   [17:0] realStream_dout;
wire   [1:0] realStream_num_data_valid;
wire   [1:0] realStream_fifo_cap;
wire    realStream_empty_n;
wire    imgStream_full_n;
wire   [17:0] imgStream_dout;
wire   [1:0] imgStream_num_data_valid;
wire   [1:0] imgStream_fifo_cap;
wire    imgStream_empty_n;
wire    inputLength_c_full_n;
wire   [31:0] inputLength_c_dout;
wire   [1:0] inputLength_c_num_data_valid;
wire   [1:0] inputLength_c_fifo_cap;
wire    inputLength_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_complexFIR_U0_ap_ready;
wire    ap_sync_complexFIR_U0_ap_ready;
wire   [0:0] start_for_bulkCordicConvert_U0_din;
wire    start_for_bulkCordicConvert_U0_full_n;
wire   [0:0] start_for_bulkCordicConvert_U0_dout;
wire    start_for_bulkCordicConvert_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_complexFIR_U0_ap_ready = 1'b0;
end

polarFir_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .inputReal(inputReal),
    .inputImg(inputImg),
    .outputMag(outputMag),
    .outputPhase(outputPhase),
    .inputLength(inputLength),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

polarFir_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(bulkCordicConvert_U0_m_axi_gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(bulkCordicConvert_U0_m_axi_gmem_AWADDR),
    .I_AWLEN(bulkCordicConvert_U0_m_axi_gmem_AWLEN),
    .I_WVALID(bulkCordicConvert_U0_m_axi_gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(bulkCordicConvert_U0_m_axi_gmem_WDATA),
    .I_WSTRB(bulkCordicConvert_U0_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(bulkCordicConvert_U0_m_axi_gmem_BREADY)
);

polarFir_imgIn_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IMGIN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IMGIN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IMGIN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IMGIN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IMGIN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IMGIN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IMGIN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IMGIN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_IMGIN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IMGIN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IMGIN_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
imgIn_m_axi_U(
    .AWVALID(m_axi_imgIn_AWVALID),
    .AWREADY(m_axi_imgIn_AWREADY),
    .AWADDR(m_axi_imgIn_AWADDR),
    .AWID(m_axi_imgIn_AWID),
    .AWLEN(m_axi_imgIn_AWLEN),
    .AWSIZE(m_axi_imgIn_AWSIZE),
    .AWBURST(m_axi_imgIn_AWBURST),
    .AWLOCK(m_axi_imgIn_AWLOCK),
    .AWCACHE(m_axi_imgIn_AWCACHE),
    .AWPROT(m_axi_imgIn_AWPROT),
    .AWQOS(m_axi_imgIn_AWQOS),
    .AWREGION(m_axi_imgIn_AWREGION),
    .AWUSER(m_axi_imgIn_AWUSER),
    .WVALID(m_axi_imgIn_WVALID),
    .WREADY(m_axi_imgIn_WREADY),
    .WDATA(m_axi_imgIn_WDATA),
    .WSTRB(m_axi_imgIn_WSTRB),
    .WLAST(m_axi_imgIn_WLAST),
    .WID(m_axi_imgIn_WID),
    .WUSER(m_axi_imgIn_WUSER),
    .ARVALID(m_axi_imgIn_ARVALID),
    .ARREADY(m_axi_imgIn_ARREADY),
    .ARADDR(m_axi_imgIn_ARADDR),
    .ARID(m_axi_imgIn_ARID),
    .ARLEN(m_axi_imgIn_ARLEN),
    .ARSIZE(m_axi_imgIn_ARSIZE),
    .ARBURST(m_axi_imgIn_ARBURST),
    .ARLOCK(m_axi_imgIn_ARLOCK),
    .ARCACHE(m_axi_imgIn_ARCACHE),
    .ARPROT(m_axi_imgIn_ARPROT),
    .ARQOS(m_axi_imgIn_ARQOS),
    .ARREGION(m_axi_imgIn_ARREGION),
    .ARUSER(m_axi_imgIn_ARUSER),
    .RVALID(m_axi_imgIn_RVALID),
    .RREADY(m_axi_imgIn_RREADY),
    .RDATA(m_axi_imgIn_RDATA),
    .RLAST(m_axi_imgIn_RLAST),
    .RID(m_axi_imgIn_RID),
    .RUSER(m_axi_imgIn_RUSER),
    .RRESP(m_axi_imgIn_RRESP),
    .BVALID(m_axi_imgIn_BVALID),
    .BREADY(m_axi_imgIn_BREADY),
    .BRESP(m_axi_imgIn_BRESP),
    .BID(m_axi_imgIn_BID),
    .BUSER(m_axi_imgIn_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(complexFIR_U0_m_axi_imgIn_ARVALID),
    .I_ARREADY(imgIn_ARREADY),
    .I_ARADDR(complexFIR_U0_m_axi_imgIn_ARADDR),
    .I_ARLEN(complexFIR_U0_m_axi_imgIn_ARLEN),
    .I_RVALID(imgIn_RVALID),
    .I_RREADY(complexFIR_U0_m_axi_imgIn_RREADY),
    .I_RDATA(imgIn_RDATA),
    .I_RFIFONUM(imgIn_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(imgIn_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(imgIn_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(imgIn_BVALID),
    .I_BREADY(1'b0)
);

polarFir_realIn_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_REALIN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_REALIN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_REALIN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_REALIN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_REALIN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_REALIN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_REALIN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_REALIN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_REALIN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_REALIN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_REALIN_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
realIn_m_axi_U(
    .AWVALID(m_axi_realIn_AWVALID),
    .AWREADY(m_axi_realIn_AWREADY),
    .AWADDR(m_axi_realIn_AWADDR),
    .AWID(m_axi_realIn_AWID),
    .AWLEN(m_axi_realIn_AWLEN),
    .AWSIZE(m_axi_realIn_AWSIZE),
    .AWBURST(m_axi_realIn_AWBURST),
    .AWLOCK(m_axi_realIn_AWLOCK),
    .AWCACHE(m_axi_realIn_AWCACHE),
    .AWPROT(m_axi_realIn_AWPROT),
    .AWQOS(m_axi_realIn_AWQOS),
    .AWREGION(m_axi_realIn_AWREGION),
    .AWUSER(m_axi_realIn_AWUSER),
    .WVALID(m_axi_realIn_WVALID),
    .WREADY(m_axi_realIn_WREADY),
    .WDATA(m_axi_realIn_WDATA),
    .WSTRB(m_axi_realIn_WSTRB),
    .WLAST(m_axi_realIn_WLAST),
    .WID(m_axi_realIn_WID),
    .WUSER(m_axi_realIn_WUSER),
    .ARVALID(m_axi_realIn_ARVALID),
    .ARREADY(m_axi_realIn_ARREADY),
    .ARADDR(m_axi_realIn_ARADDR),
    .ARID(m_axi_realIn_ARID),
    .ARLEN(m_axi_realIn_ARLEN),
    .ARSIZE(m_axi_realIn_ARSIZE),
    .ARBURST(m_axi_realIn_ARBURST),
    .ARLOCK(m_axi_realIn_ARLOCK),
    .ARCACHE(m_axi_realIn_ARCACHE),
    .ARPROT(m_axi_realIn_ARPROT),
    .ARQOS(m_axi_realIn_ARQOS),
    .ARREGION(m_axi_realIn_ARREGION),
    .ARUSER(m_axi_realIn_ARUSER),
    .RVALID(m_axi_realIn_RVALID),
    .RREADY(m_axi_realIn_RREADY),
    .RDATA(m_axi_realIn_RDATA),
    .RLAST(m_axi_realIn_RLAST),
    .RID(m_axi_realIn_RID),
    .RUSER(m_axi_realIn_RUSER),
    .RRESP(m_axi_realIn_RRESP),
    .BVALID(m_axi_realIn_BVALID),
    .BREADY(m_axi_realIn_BREADY),
    .BRESP(m_axi_realIn_BRESP),
    .BID(m_axi_realIn_BID),
    .BUSER(m_axi_realIn_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(complexFIR_U0_m_axi_realIn_ARVALID),
    .I_ARREADY(realIn_ARREADY),
    .I_ARADDR(complexFIR_U0_m_axi_realIn_ARADDR),
    .I_ARLEN(complexFIR_U0_m_axi_realIn_ARLEN),
    .I_RVALID(realIn_RVALID),
    .I_RREADY(complexFIR_U0_m_axi_realIn_RREADY),
    .I_RDATA(realIn_RDATA),
    .I_RFIFONUM(realIn_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(realIn_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(realIn_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(realIn_BVALID),
    .I_BREADY(1'b0)
);

polarFir_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_bulkCordicConvert_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .outputMag(outputMag),
    .outputMag_c_din(entry_proc_U0_outputMag_c_din),
    .outputMag_c_num_data_valid(outputMag_c_num_data_valid),
    .outputMag_c_fifo_cap(outputMag_c_fifo_cap),
    .outputMag_c_full_n(outputMag_c_full_n),
    .outputMag_c_write(entry_proc_U0_outputMag_c_write),
    .outputPhase(outputPhase),
    .outputPhase_c_din(entry_proc_U0_outputPhase_c_din),
    .outputPhase_c_num_data_valid(outputPhase_c_num_data_valid),
    .outputPhase_c_fifo_cap(outputPhase_c_fifo_cap),
    .outputPhase_c_full_n(outputPhase_c_full_n),
    .outputPhase_c_write(entry_proc_U0_outputPhase_c_write)
);

polarFir_complexFIR complexFIR_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(complexFIR_U0_ap_start),
    .ap_done(complexFIR_U0_ap_done),
    .ap_continue(complexFIR_U0_ap_continue),
    .ap_idle(complexFIR_U0_ap_idle),
    .ap_ready(complexFIR_U0_ap_ready),
    .m_axi_realIn_AWVALID(complexFIR_U0_m_axi_realIn_AWVALID),
    .m_axi_realIn_AWREADY(1'b0),
    .m_axi_realIn_AWADDR(complexFIR_U0_m_axi_realIn_AWADDR),
    .m_axi_realIn_AWID(complexFIR_U0_m_axi_realIn_AWID),
    .m_axi_realIn_AWLEN(complexFIR_U0_m_axi_realIn_AWLEN),
    .m_axi_realIn_AWSIZE(complexFIR_U0_m_axi_realIn_AWSIZE),
    .m_axi_realIn_AWBURST(complexFIR_U0_m_axi_realIn_AWBURST),
    .m_axi_realIn_AWLOCK(complexFIR_U0_m_axi_realIn_AWLOCK),
    .m_axi_realIn_AWCACHE(complexFIR_U0_m_axi_realIn_AWCACHE),
    .m_axi_realIn_AWPROT(complexFIR_U0_m_axi_realIn_AWPROT),
    .m_axi_realIn_AWQOS(complexFIR_U0_m_axi_realIn_AWQOS),
    .m_axi_realIn_AWREGION(complexFIR_U0_m_axi_realIn_AWREGION),
    .m_axi_realIn_AWUSER(complexFIR_U0_m_axi_realIn_AWUSER),
    .m_axi_realIn_WVALID(complexFIR_U0_m_axi_realIn_WVALID),
    .m_axi_realIn_WREADY(1'b0),
    .m_axi_realIn_WDATA(complexFIR_U0_m_axi_realIn_WDATA),
    .m_axi_realIn_WSTRB(complexFIR_U0_m_axi_realIn_WSTRB),
    .m_axi_realIn_WLAST(complexFIR_U0_m_axi_realIn_WLAST),
    .m_axi_realIn_WID(complexFIR_U0_m_axi_realIn_WID),
    .m_axi_realIn_WUSER(complexFIR_U0_m_axi_realIn_WUSER),
    .m_axi_realIn_ARVALID(complexFIR_U0_m_axi_realIn_ARVALID),
    .m_axi_realIn_ARREADY(realIn_ARREADY),
    .m_axi_realIn_ARADDR(complexFIR_U0_m_axi_realIn_ARADDR),
    .m_axi_realIn_ARID(complexFIR_U0_m_axi_realIn_ARID),
    .m_axi_realIn_ARLEN(complexFIR_U0_m_axi_realIn_ARLEN),
    .m_axi_realIn_ARSIZE(complexFIR_U0_m_axi_realIn_ARSIZE),
    .m_axi_realIn_ARBURST(complexFIR_U0_m_axi_realIn_ARBURST),
    .m_axi_realIn_ARLOCK(complexFIR_U0_m_axi_realIn_ARLOCK),
    .m_axi_realIn_ARCACHE(complexFIR_U0_m_axi_realIn_ARCACHE),
    .m_axi_realIn_ARPROT(complexFIR_U0_m_axi_realIn_ARPROT),
    .m_axi_realIn_ARQOS(complexFIR_U0_m_axi_realIn_ARQOS),
    .m_axi_realIn_ARREGION(complexFIR_U0_m_axi_realIn_ARREGION),
    .m_axi_realIn_ARUSER(complexFIR_U0_m_axi_realIn_ARUSER),
    .m_axi_realIn_RVALID(realIn_RVALID),
    .m_axi_realIn_RREADY(complexFIR_U0_m_axi_realIn_RREADY),
    .m_axi_realIn_RDATA(realIn_RDATA),
    .m_axi_realIn_RLAST(realIn_RLAST),
    .m_axi_realIn_RID(realIn_RID),
    .m_axi_realIn_RFIFONUM(realIn_RFIFONUM),
    .m_axi_realIn_RUSER(realIn_RUSER),
    .m_axi_realIn_RRESP(realIn_RRESP),
    .m_axi_realIn_BVALID(1'b0),
    .m_axi_realIn_BREADY(complexFIR_U0_m_axi_realIn_BREADY),
    .m_axi_realIn_BRESP(2'd0),
    .m_axi_realIn_BID(1'd0),
    .m_axi_realIn_BUSER(1'd0),
    .inputReal(inputReal),
    .m_axi_imgIn_AWVALID(complexFIR_U0_m_axi_imgIn_AWVALID),
    .m_axi_imgIn_AWREADY(1'b0),
    .m_axi_imgIn_AWADDR(complexFIR_U0_m_axi_imgIn_AWADDR),
    .m_axi_imgIn_AWID(complexFIR_U0_m_axi_imgIn_AWID),
    .m_axi_imgIn_AWLEN(complexFIR_U0_m_axi_imgIn_AWLEN),
    .m_axi_imgIn_AWSIZE(complexFIR_U0_m_axi_imgIn_AWSIZE),
    .m_axi_imgIn_AWBURST(complexFIR_U0_m_axi_imgIn_AWBURST),
    .m_axi_imgIn_AWLOCK(complexFIR_U0_m_axi_imgIn_AWLOCK),
    .m_axi_imgIn_AWCACHE(complexFIR_U0_m_axi_imgIn_AWCACHE),
    .m_axi_imgIn_AWPROT(complexFIR_U0_m_axi_imgIn_AWPROT),
    .m_axi_imgIn_AWQOS(complexFIR_U0_m_axi_imgIn_AWQOS),
    .m_axi_imgIn_AWREGION(complexFIR_U0_m_axi_imgIn_AWREGION),
    .m_axi_imgIn_AWUSER(complexFIR_U0_m_axi_imgIn_AWUSER),
    .m_axi_imgIn_WVALID(complexFIR_U0_m_axi_imgIn_WVALID),
    .m_axi_imgIn_WREADY(1'b0),
    .m_axi_imgIn_WDATA(complexFIR_U0_m_axi_imgIn_WDATA),
    .m_axi_imgIn_WSTRB(complexFIR_U0_m_axi_imgIn_WSTRB),
    .m_axi_imgIn_WLAST(complexFIR_U0_m_axi_imgIn_WLAST),
    .m_axi_imgIn_WID(complexFIR_U0_m_axi_imgIn_WID),
    .m_axi_imgIn_WUSER(complexFIR_U0_m_axi_imgIn_WUSER),
    .m_axi_imgIn_ARVALID(complexFIR_U0_m_axi_imgIn_ARVALID),
    .m_axi_imgIn_ARREADY(imgIn_ARREADY),
    .m_axi_imgIn_ARADDR(complexFIR_U0_m_axi_imgIn_ARADDR),
    .m_axi_imgIn_ARID(complexFIR_U0_m_axi_imgIn_ARID),
    .m_axi_imgIn_ARLEN(complexFIR_U0_m_axi_imgIn_ARLEN),
    .m_axi_imgIn_ARSIZE(complexFIR_U0_m_axi_imgIn_ARSIZE),
    .m_axi_imgIn_ARBURST(complexFIR_U0_m_axi_imgIn_ARBURST),
    .m_axi_imgIn_ARLOCK(complexFIR_U0_m_axi_imgIn_ARLOCK),
    .m_axi_imgIn_ARCACHE(complexFIR_U0_m_axi_imgIn_ARCACHE),
    .m_axi_imgIn_ARPROT(complexFIR_U0_m_axi_imgIn_ARPROT),
    .m_axi_imgIn_ARQOS(complexFIR_U0_m_axi_imgIn_ARQOS),
    .m_axi_imgIn_ARREGION(complexFIR_U0_m_axi_imgIn_ARREGION),
    .m_axi_imgIn_ARUSER(complexFIR_U0_m_axi_imgIn_ARUSER),
    .m_axi_imgIn_RVALID(imgIn_RVALID),
    .m_axi_imgIn_RREADY(complexFIR_U0_m_axi_imgIn_RREADY),
    .m_axi_imgIn_RDATA(imgIn_RDATA),
    .m_axi_imgIn_RLAST(imgIn_RLAST),
    .m_axi_imgIn_RID(imgIn_RID),
    .m_axi_imgIn_RFIFONUM(imgIn_RFIFONUM),
    .m_axi_imgIn_RUSER(imgIn_RUSER),
    .m_axi_imgIn_RRESP(imgIn_RRESP),
    .m_axi_imgIn_BVALID(1'b0),
    .m_axi_imgIn_BREADY(complexFIR_U0_m_axi_imgIn_BREADY),
    .m_axi_imgIn_BRESP(2'd0),
    .m_axi_imgIn_BID(1'd0),
    .m_axi_imgIn_BUSER(1'd0),
    .inputImg(inputImg),
    .realStream2_din(complexFIR_U0_realStream2_din),
    .realStream2_num_data_valid(realStream_num_data_valid),
    .realStream2_fifo_cap(realStream_fifo_cap),
    .realStream2_full_n(realStream_full_n),
    .realStream2_write(complexFIR_U0_realStream2_write),
    .imgStream3_din(complexFIR_U0_imgStream3_din),
    .imgStream3_num_data_valid(imgStream_num_data_valid),
    .imgStream3_fifo_cap(imgStream_fifo_cap),
    .imgStream3_full_n(imgStream_full_n),
    .imgStream3_write(complexFIR_U0_imgStream3_write),
    .filterLength(inputLength),
    .inputLength_c_din(complexFIR_U0_inputLength_c_din),
    .inputLength_c_num_data_valid(inputLength_c_num_data_valid),
    .inputLength_c_fifo_cap(inputLength_c_fifo_cap),
    .inputLength_c_full_n(inputLength_c_full_n),
    .inputLength_c_write(complexFIR_U0_inputLength_c_write)
);

polarFir_bulkCordicConvert bulkCordicConvert_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(bulkCordicConvert_U0_ap_start),
    .ap_done(bulkCordicConvert_U0_ap_done),
    .ap_continue(bulkCordicConvert_U0_ap_continue),
    .ap_idle(bulkCordicConvert_U0_ap_idle),
    .ap_ready(bulkCordicConvert_U0_ap_ready),
    .realStream2_dout(realStream_dout),
    .realStream2_num_data_valid(realStream_num_data_valid),
    .realStream2_fifo_cap(realStream_fifo_cap),
    .realStream2_empty_n(realStream_empty_n),
    .realStream2_read(bulkCordicConvert_U0_realStream2_read),
    .imgStream3_dout(imgStream_dout),
    .imgStream3_num_data_valid(imgStream_num_data_valid),
    .imgStream3_fifo_cap(imgStream_fifo_cap),
    .imgStream3_empty_n(imgStream_empty_n),
    .imgStream3_read(bulkCordicConvert_U0_imgStream3_read),
    .m_axi_gmem_AWVALID(bulkCordicConvert_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(bulkCordicConvert_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(bulkCordicConvert_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(bulkCordicConvert_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(bulkCordicConvert_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(bulkCordicConvert_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(bulkCordicConvert_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(bulkCordicConvert_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(bulkCordicConvert_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(bulkCordicConvert_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(bulkCordicConvert_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(bulkCordicConvert_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(bulkCordicConvert_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(bulkCordicConvert_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(bulkCordicConvert_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(bulkCordicConvert_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(bulkCordicConvert_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(bulkCordicConvert_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(bulkCordicConvert_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(bulkCordicConvert_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(bulkCordicConvert_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(bulkCordicConvert_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(bulkCordicConvert_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(bulkCordicConvert_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(bulkCordicConvert_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(bulkCordicConvert_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(bulkCordicConvert_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(bulkCordicConvert_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(bulkCordicConvert_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(bulkCordicConvert_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(bulkCordicConvert_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(bulkCordicConvert_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(gmem_BRESP),
    .m_axi_gmem_BID(gmem_BID),
    .m_axi_gmem_BUSER(gmem_BUSER),
    .mag_dout(outputMag_c_dout),
    .mag_num_data_valid(outputMag_c_num_data_valid),
    .mag_fifo_cap(outputMag_c_fifo_cap),
    .mag_empty_n(outputMag_c_empty_n),
    .mag_read(bulkCordicConvert_U0_mag_read),
    .theta_dout(outputPhase_c_dout),
    .theta_num_data_valid(outputPhase_c_num_data_valid),
    .theta_fifo_cap(outputPhase_c_fifo_cap),
    .theta_empty_n(outputPhase_c_empty_n),
    .theta_read(bulkCordicConvert_U0_theta_read),
    .convertSize_dout(inputLength_c_dout),
    .convertSize_num_data_valid(inputLength_c_num_data_valid),
    .convertSize_fifo_cap(inputLength_c_fifo_cap),
    .convertSize_empty_n(inputLength_c_empty_n),
    .convertSize_read(bulkCordicConvert_U0_convertSize_read)
);

polarFir_fifo_w64_d3_S outputMag_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_outputMag_c_din),
    .if_full_n(outputMag_c_full_n),
    .if_write(entry_proc_U0_outputMag_c_write),
    .if_dout(outputMag_c_dout),
    .if_num_data_valid(outputMag_c_num_data_valid),
    .if_fifo_cap(outputMag_c_fifo_cap),
    .if_empty_n(outputMag_c_empty_n),
    .if_read(bulkCordicConvert_U0_mag_read)
);

polarFir_fifo_w64_d3_S outputPhase_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_outputPhase_c_din),
    .if_full_n(outputPhase_c_full_n),
    .if_write(entry_proc_U0_outputPhase_c_write),
    .if_dout(outputPhase_c_dout),
    .if_num_data_valid(outputPhase_c_num_data_valid),
    .if_fifo_cap(outputPhase_c_fifo_cap),
    .if_empty_n(outputPhase_c_empty_n),
    .if_read(bulkCordicConvert_U0_theta_read)
);

polarFir_fifo_w18_d2_S realStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(complexFIR_U0_realStream2_din),
    .if_full_n(realStream_full_n),
    .if_write(complexFIR_U0_realStream2_write),
    .if_dout(realStream_dout),
    .if_num_data_valid(realStream_num_data_valid),
    .if_fifo_cap(realStream_fifo_cap),
    .if_empty_n(realStream_empty_n),
    .if_read(bulkCordicConvert_U0_realStream2_read)
);

polarFir_fifo_w18_d2_S imgStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(complexFIR_U0_imgStream3_din),
    .if_full_n(imgStream_full_n),
    .if_write(complexFIR_U0_imgStream3_write),
    .if_dout(imgStream_dout),
    .if_num_data_valid(imgStream_num_data_valid),
    .if_fifo_cap(imgStream_fifo_cap),
    .if_empty_n(imgStream_empty_n),
    .if_read(bulkCordicConvert_U0_imgStream3_read)
);

polarFir_fifo_w32_d2_S inputLength_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(complexFIR_U0_inputLength_c_din),
    .if_full_n(inputLength_c_full_n),
    .if_write(complexFIR_U0_inputLength_c_write),
    .if_dout(inputLength_c_dout),
    .if_num_data_valid(inputLength_c_num_data_valid),
    .if_fifo_cap(inputLength_c_fifo_cap),
    .if_empty_n(inputLength_c_empty_n),
    .if_read(bulkCordicConvert_U0_convertSize_read)
);

polarFir_start_for_bulkCordicConvert_U0 start_for_bulkCordicConvert_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_bulkCordicConvert_U0_din),
    .if_full_n(start_for_bulkCordicConvert_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_bulkCordicConvert_U0_dout),
    .if_empty_n(start_for_bulkCordicConvert_U0_empty_n),
    .if_read(bulkCordicConvert_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_complexFIR_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_complexFIR_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_complexFIR_U0_ap_ready <= ap_sync_complexFIR_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign ap_done = bulkCordicConvert_U0_ap_done;

assign ap_idle = (entry_proc_U0_ap_idle & complexFIR_U0_ap_idle & bulkCordicConvert_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_complexFIR_U0_ap_ready = (complexFIR_U0_ap_ready | ap_sync_reg_complexFIR_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_complexFIR_U0_ap_ready);

assign bulkCordicConvert_U0_ap_continue = 1'b1;

assign bulkCordicConvert_U0_ap_start = start_for_bulkCordicConvert_U0_empty_n;

assign complexFIR_U0_ap_continue = 1'b1;

assign complexFIR_U0_ap_start = ((ap_sync_reg_complexFIR_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem_BID = 1'd0;

assign gmem_BRESP = 2'd0;

assign gmem_BUSER = 1'd0;

assign imgIn_RID = 1'd0;

assign imgIn_RLAST = 1'b0;

assign imgIn_RRESP = 2'd0;

assign imgIn_RUSER = 1'd0;

assign realIn_RID = 1'd0;

assign realIn_RLAST = 1'b0;

assign realIn_RRESP = 2'd0;

assign realIn_RUSER = 1'd0;

assign start_for_bulkCordicConvert_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "polarFir_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //polarFir

