// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module polarFir_computeComplexFIR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inputReal,
        inputImg,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] inputReal;
input  [5:0] inputImg;
input  [5:0] p_read;
input  [5:0] p_read1;
input  [5:0] p_read2;
input  [5:0] p_read3;
input  [5:0] p_read4;
input  [5:0] p_read5;
input  [5:0] p_read6;
input  [5:0] p_read7;
input  [5:0] p_read8;
input  [5:0] p_read9;
input  [5:0] p_read10;
input  [5:0] p_read11;
input  [5:0] p_read12;
input  [5:0] p_read13;
input  [5:0] p_read14;
input  [5:0] p_read15;
input  [5:0] p_read16;
input  [5:0] p_read17;
input  [5:0] p_read18;
input  [5:0] p_read19;
input  [5:0] p_read20;
input  [5:0] p_read21;
input  [5:0] p_read22;
input  [5:0] p_read23;
input  [5:0] p_read24;
input  [5:0] p_read25;
input  [5:0] p_read26;
input  [5:0] p_read27;
input  [5:0] p_read28;
input  [5:0] p_read29;
input  [5:0] p_read30;
input  [5:0] p_read31;
input  [5:0] p_read32;
input  [5:0] p_read33;
input  [5:0] p_read34;
input  [5:0] p_read35;
input  [5:0] p_read36;
input  [5:0] p_read37;
input  [5:0] p_read38;
input  [5:0] p_read39;
input  [5:0] p_read40;
input  [5:0] p_read41;
input  [5:0] p_read42;
input  [5:0] p_read43;
input  [5:0] p_read44;
input  [5:0] p_read45;
input  [5:0] p_read46;
input  [5:0] p_read47;
input  [5:0] p_read48;
input  [5:0] p_read49;
output  [17:0] ap_return_0;
output  [17:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698;
reg   [5:0] computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708;
reg   [5:0] p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803;
reg   [5:0] computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808;
reg   [5:0] computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813;
wire  signed [11:0] sext_ln1494_1_fu_1138_p1;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln140_fu_1060_p2;
wire   [11:0] ret_V_6_fu_1142_p2;
reg   [11:0] ret_V_6_reg_1826;
reg  signed [11:0] ret_V_6_reg_1826_pp0_iter1_reg;
wire  signed [11:0] sext_ln1494_2_fu_1210_p1;
wire  signed [11:0] sext_ln1494_3_fu_1214_p1;
wire   [11:0] ret_V_8_fu_1218_p2;
reg   [11:0] ret_V_8_reg_1842;
reg  signed [11:0] ret_V_8_reg_1842_pp0_iter1_reg;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [16:0] resultReal_V_fu_232;
wire   [16:0] resultReal_V_1_fu_1235_p2;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_state6;
reg   [16:0] resultImg_V_fu_236;
wire   [16:0] resultImg_V_1_fu_1244_p2;
reg   [4:0] j_fu_240;
wire   [4:0] add_ln140_fu_1066_p2;
wire   [5:0] tmp_fu_1072_p27;
wire   [5:0] tmp_1_fu_1103_p27;
wire  signed [5:0] ret_V_6_fu_1142_p0;
wire  signed [5:0] ret_V_6_fu_1142_p1;
wire  signed [11:0] sext_ln1494_fu_1134_p1;
wire   [5:0] tmp_2_fu_1148_p27;
wire   [5:0] tmp_3_fu_1179_p27;
wire  signed [5:0] ret_V_8_fu_1218_p0;
wire  signed [5:0] ret_V_8_fu_1218_p1;
wire  signed [11:0] grp_fu_1280_p3;
wire  signed [16:0] sext_ln840_fu_1232_p1;
wire  signed [12:0] grp_fu_1288_p3;
wire  signed [16:0] sext_ln840_1_fu_1241_p1;
wire  signed [17:0] sext_ln140_fu_1260_p1;
wire  signed [17:0] sext_ln140_1_fu_1264_p1;
wire  signed [5:0] grp_fu_1280_p0;
wire  signed [5:0] grp_fu_1280_p1;
wire  signed [5:0] grp_fu_1288_p0;
wire  signed [5:0] grp_fu_1288_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10 = 6'd0;
#0 p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9 = 6'd0;
#0 computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9 = 6'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

polarFir_mux_255_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .din4_WIDTH( 6 ),
    .din5_WIDTH( 6 ),
    .din6_WIDTH( 6 ),
    .din7_WIDTH( 6 ),
    .din8_WIDTH( 6 ),
    .din9_WIDTH( 6 ),
    .din10_WIDTH( 6 ),
    .din11_WIDTH( 6 ),
    .din12_WIDTH( 6 ),
    .din13_WIDTH( 6 ),
    .din14_WIDTH( 6 ),
    .din15_WIDTH( 6 ),
    .din16_WIDTH( 6 ),
    .din17_WIDTH( 6 ),
    .din18_WIDTH( 6 ),
    .din19_WIDTH( 6 ),
    .din20_WIDTH( 6 ),
    .din21_WIDTH( 6 ),
    .din22_WIDTH( 6 ),
    .din23_WIDTH( 6 ),
    .din24_WIDTH( 6 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mux_255_6_1_1_U5(
    .din0(inputReal),
    .din1(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808),
    .din2(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798),
    .din3(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788),
    .din4(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778),
    .din5(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768),
    .din6(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758),
    .din7(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748),
    .din8(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738),
    .din9(computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728),
    .din10(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718),
    .din11(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708),
    .din12(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698),
    .din13(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688),
    .din14(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678),
    .din15(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668),
    .din16(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658),
    .din17(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648),
    .din18(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638),
    .din19(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628),
    .din20(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618),
    .din21(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608),
    .din22(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598),
    .din23(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588),
    .din24(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578),
    .din25(j_fu_240),
    .dout(tmp_fu_1072_p27)
);

polarFir_mux_255_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .din4_WIDTH( 6 ),
    .din5_WIDTH( 6 ),
    .din6_WIDTH( 6 ),
    .din7_WIDTH( 6 ),
    .din8_WIDTH( 6 ),
    .din9_WIDTH( 6 ),
    .din10_WIDTH( 6 ),
    .din11_WIDTH( 6 ),
    .din12_WIDTH( 6 ),
    .din13_WIDTH( 6 ),
    .din14_WIDTH( 6 ),
    .din15_WIDTH( 6 ),
    .din16_WIDTH( 6 ),
    .din17_WIDTH( 6 ),
    .din18_WIDTH( 6 ),
    .din19_WIDTH( 6 ),
    .din20_WIDTH( 6 ),
    .din21_WIDTH( 6 ),
    .din22_WIDTH( 6 ),
    .din23_WIDTH( 6 ),
    .din24_WIDTH( 6 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mux_255_6_1_1_U6(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .din4(p_read4),
    .din5(p_read5),
    .din6(p_read6),
    .din7(p_read7),
    .din8(p_read8),
    .din9(p_read9),
    .din10(p_read10),
    .din11(p_read11),
    .din12(p_read12),
    .din13(p_read13),
    .din14(p_read14),
    .din15(p_read15),
    .din16(p_read16),
    .din17(p_read17),
    .din18(p_read18),
    .din19(p_read19),
    .din20(p_read20),
    .din21(p_read21),
    .din22(p_read22),
    .din23(p_read23),
    .din24(p_read24),
    .din25(j_fu_240),
    .dout(tmp_1_fu_1103_p27)
);

polarFir_mul_6s_6s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6s_6s_12_1_1_U7(
    .din0(ret_V_6_fu_1142_p0),
    .din1(ret_V_6_fu_1142_p1),
    .dout(ret_V_6_fu_1142_p2)
);

polarFir_mux_255_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .din4_WIDTH( 6 ),
    .din5_WIDTH( 6 ),
    .din6_WIDTH( 6 ),
    .din7_WIDTH( 6 ),
    .din8_WIDTH( 6 ),
    .din9_WIDTH( 6 ),
    .din10_WIDTH( 6 ),
    .din11_WIDTH( 6 ),
    .din12_WIDTH( 6 ),
    .din13_WIDTH( 6 ),
    .din14_WIDTH( 6 ),
    .din15_WIDTH( 6 ),
    .din16_WIDTH( 6 ),
    .din17_WIDTH( 6 ),
    .din18_WIDTH( 6 ),
    .din19_WIDTH( 6 ),
    .din20_WIDTH( 6 ),
    .din21_WIDTH( 6 ),
    .din22_WIDTH( 6 ),
    .din23_WIDTH( 6 ),
    .din24_WIDTH( 6 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mux_255_6_1_1_U8(
    .din0(inputImg),
    .din1(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813),
    .din2(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803),
    .din3(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793),
    .din4(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783),
    .din5(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773),
    .din6(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763),
    .din7(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753),
    .din8(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743),
    .din9(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733),
    .din10(computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723),
    .din11(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713),
    .din12(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703),
    .din13(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693),
    .din14(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683),
    .din15(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673),
    .din16(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663),
    .din17(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653),
    .din18(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643),
    .din19(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633),
    .din20(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623),
    .din21(p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613),
    .din22(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603),
    .din23(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593),
    .din24(computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583),
    .din25(j_fu_240),
    .dout(tmp_2_fu_1148_p27)
);

polarFir_mux_255_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .din4_WIDTH( 6 ),
    .din5_WIDTH( 6 ),
    .din6_WIDTH( 6 ),
    .din7_WIDTH( 6 ),
    .din8_WIDTH( 6 ),
    .din9_WIDTH( 6 ),
    .din10_WIDTH( 6 ),
    .din11_WIDTH( 6 ),
    .din12_WIDTH( 6 ),
    .din13_WIDTH( 6 ),
    .din14_WIDTH( 6 ),
    .din15_WIDTH( 6 ),
    .din16_WIDTH( 6 ),
    .din17_WIDTH( 6 ),
    .din18_WIDTH( 6 ),
    .din19_WIDTH( 6 ),
    .din20_WIDTH( 6 ),
    .din21_WIDTH( 6 ),
    .din22_WIDTH( 6 ),
    .din23_WIDTH( 6 ),
    .din24_WIDTH( 6 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mux_255_6_1_1_U9(
    .din0(p_read25),
    .din1(p_read26),
    .din2(p_read27),
    .din3(p_read28),
    .din4(p_read29),
    .din5(p_read30),
    .din6(p_read31),
    .din7(p_read32),
    .din8(p_read33),
    .din9(p_read34),
    .din10(p_read35),
    .din11(p_read36),
    .din12(p_read37),
    .din13(p_read38),
    .din14(p_read39),
    .din15(p_read40),
    .din16(p_read41),
    .din17(p_read42),
    .din18(p_read43),
    .din19(p_read44),
    .din20(p_read45),
    .din21(p_read46),
    .din22(p_read47),
    .din23(p_read48),
    .din24(p_read49),
    .din25(j_fu_240),
    .dout(tmp_3_fu_1179_p27)
);

polarFir_mul_6s_6s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6s_6s_12_1_1_U10(
    .din0(ret_V_8_fu_1218_p0),
    .din1(ret_V_8_fu_1218_p1),
    .dout(ret_V_8_fu_1218_p2)
);

polarFir_mac_mulsub_6s_6s_12s_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
mac_mulsub_6s_6s_12s_12_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1280_p0),
    .din1(grp_fu_1280_p1),
    .din2(ret_V_6_reg_1826_pp0_iter1_reg),
    .ce(1'b1),
    .dout(grp_fu_1280_p3)
);

polarFir_mac_muladd_6s_6s_12s_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 13 ))
mac_muladd_6s_6s_12s_13_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1288_p0),
    .din1(grp_fu_1288_p1),
    .din2(ret_V_8_reg_1842_pp0_iter1_reg),
    .ce(1'b1),
    .dout(grp_fu_1288_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_240 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln140_fu_1060_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_240 <= add_ln140_fu_1066_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        resultImg_V_fu_236 <= 17'd0;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        resultImg_V_fu_236 <= resultImg_V_1_fu_1244_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        resultReal_V_fu_232 <= 17'd0;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        resultReal_V_fu_232 <= resultReal_V_1_fu_1235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11;
        computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8;
        computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9 <= inputImg;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9;
        computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9 <= inputReal;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21;
        p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln140_fu_1060_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_V_6_reg_1826 <= ret_V_6_fu_1142_p2;
        ret_V_8_reg_1842 <= ret_V_8_fu_1218_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_V_6_reg_1826_pp0_iter1_reg <= ret_V_6_reg_1826;
        ret_V_8_reg_1842_pp0_iter1_reg <= ret_V_8_reg_1842;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln140_fu_1060_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln140_fu_1060_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln140_fu_1060_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln140_fu_1066_p2 = (j_fu_240 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = sext_ln140_fu_1260_p1;

assign ap_return_1 = sext_ln140_1_fu_1264_p1;

assign grp_fu_1280_p0 = sext_ln1494_3_fu_1214_p1;

assign grp_fu_1280_p1 = sext_ln1494_2_fu_1210_p1;

assign grp_fu_1288_p0 = sext_ln1494_2_fu_1210_p1;

assign grp_fu_1288_p1 = sext_ln1494_1_fu_1138_p1;

assign icmp_ln140_fu_1060_p2 = ((j_fu_240 == 5'd25) ? 1'b1 : 1'b0);

assign resultImg_V_1_fu_1244_p2 = ($signed(sext_ln840_1_fu_1241_p1) + $signed(resultImg_V_fu_236));

assign resultReal_V_1_fu_1235_p2 = ($signed(sext_ln840_fu_1232_p1) + $signed(resultReal_V_fu_232));

assign ret_V_6_fu_1142_p0 = sext_ln1494_1_fu_1138_p1;

assign ret_V_6_fu_1142_p1 = sext_ln1494_fu_1134_p1;

assign ret_V_8_fu_1218_p0 = sext_ln1494_3_fu_1214_p1;

assign ret_V_8_fu_1218_p1 = sext_ln1494_fu_1134_p1;

assign sext_ln140_1_fu_1264_p1 = $signed(resultImg_V_fu_236);

assign sext_ln140_fu_1260_p1 = $signed(resultReal_V_fu_232);

assign sext_ln1494_1_fu_1138_p1 = $signed(tmp_1_fu_1103_p27);

assign sext_ln1494_2_fu_1210_p1 = $signed(tmp_2_fu_1148_p27);

assign sext_ln1494_3_fu_1214_p1 = $signed(tmp_3_fu_1179_p27);

assign sext_ln1494_fu_1134_p1 = $signed(tmp_fu_1072_p27);

assign sext_ln840_1_fu_1241_p1 = grp_fu_1288_p3;

assign sext_ln840_fu_1232_p1 = grp_fu_1280_p3;

endmodule //polarFir_computeComplexFIR
