-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity polarFir_computeComplexFIR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    inputReal : IN STD_LOGIC_VECTOR (5 downto 0);
    inputImg : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (5 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of polarFir_computeComplexFIR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808 : STD_LOGIC_VECTOR (5 downto 0);
    signal computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1494_1_fu_1138_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln140_fu_1060_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_6_fu_1142_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_6_reg_1826 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_6_reg_1826_pp0_iter1_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1494_2_fu_1210_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1494_3_fu_1214_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_8_fu_1218_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_8_reg_1842 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_8_reg_1842_pp0_iter1_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal resultReal_V_fu_232 : STD_LOGIC_VECTOR (16 downto 0);
    signal resultReal_V_1_fu_1235_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal resultImg_V_fu_236 : STD_LOGIC_VECTOR (16 downto 0);
    signal resultImg_V_1_fu_1244_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal j_fu_240 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln140_fu_1066_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_1072_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_1103_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_6_fu_1142_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_6_fu_1142_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1494_fu_1134_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_1148_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_3_fu_1179_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_8_fu_1218_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal ret_V_8_fu_1218_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_1280_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln840_fu_1232_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1288_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln840_1_fu_1241_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln140_fu_1260_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln140_1_fu_1264_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_1280_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_1280_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_1288_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_1288_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component polarFir_mux_255_6_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        din4 : IN STD_LOGIC_VECTOR (5 downto 0);
        din5 : IN STD_LOGIC_VECTOR (5 downto 0);
        din6 : IN STD_LOGIC_VECTOR (5 downto 0);
        din7 : IN STD_LOGIC_VECTOR (5 downto 0);
        din8 : IN STD_LOGIC_VECTOR (5 downto 0);
        din9 : IN STD_LOGIC_VECTOR (5 downto 0);
        din10 : IN STD_LOGIC_VECTOR (5 downto 0);
        din11 : IN STD_LOGIC_VECTOR (5 downto 0);
        din12 : IN STD_LOGIC_VECTOR (5 downto 0);
        din13 : IN STD_LOGIC_VECTOR (5 downto 0);
        din14 : IN STD_LOGIC_VECTOR (5 downto 0);
        din15 : IN STD_LOGIC_VECTOR (5 downto 0);
        din16 : IN STD_LOGIC_VECTOR (5 downto 0);
        din17 : IN STD_LOGIC_VECTOR (5 downto 0);
        din18 : IN STD_LOGIC_VECTOR (5 downto 0);
        din19 : IN STD_LOGIC_VECTOR (5 downto 0);
        din20 : IN STD_LOGIC_VECTOR (5 downto 0);
        din21 : IN STD_LOGIC_VECTOR (5 downto 0);
        din22 : IN STD_LOGIC_VECTOR (5 downto 0);
        din23 : IN STD_LOGIC_VECTOR (5 downto 0);
        din24 : IN STD_LOGIC_VECTOR (5 downto 0);
        din25 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component polarFir_mul_6s_6s_12_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component polarFir_mac_mulsub_6s_6s_12s_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component polarFir_mac_muladd_6s_6s_12s_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;



begin
    mux_255_6_1_1_U5 : component polarFir_mux_255_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 6,
        din13_WIDTH => 6,
        din14_WIDTH => 6,
        din15_WIDTH => 6,
        din16_WIDTH => 6,
        din17_WIDTH => 6,
        din18_WIDTH => 6,
        din19_WIDTH => 6,
        din20_WIDTH => 6,
        din21_WIDTH => 6,
        din22_WIDTH => 6,
        din23_WIDTH => 6,
        din24_WIDTH => 6,
        din25_WIDTH => 5,
        dout_WIDTH => 6)
    port map (
        din0 => inputReal,
        din1 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808,
        din2 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798,
        din3 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788,
        din4 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778,
        din5 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768,
        din6 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758,
        din7 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748,
        din8 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738,
        din9 => computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728,
        din10 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718,
        din11 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708,
        din12 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698,
        din13 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688,
        din14 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678,
        din15 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668,
        din16 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658,
        din17 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648,
        din18 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638,
        din19 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628,
        din20 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618,
        din21 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608,
        din22 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598,
        din23 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588,
        din24 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578,
        din25 => j_fu_240,
        dout => tmp_fu_1072_p27);

    mux_255_6_1_1_U6 : component polarFir_mux_255_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 6,
        din13_WIDTH => 6,
        din14_WIDTH => 6,
        din15_WIDTH => 6,
        din16_WIDTH => 6,
        din17_WIDTH => 6,
        din18_WIDTH => 6,
        din19_WIDTH => 6,
        din20_WIDTH => 6,
        din21_WIDTH => 6,
        din22_WIDTH => 6,
        din23_WIDTH => 6,
        din24_WIDTH => 6,
        din25_WIDTH => 5,
        dout_WIDTH => 6)
    port map (
        din0 => p_read,
        din1 => p_read1,
        din2 => p_read2,
        din3 => p_read3,
        din4 => p_read4,
        din5 => p_read5,
        din6 => p_read6,
        din7 => p_read7,
        din8 => p_read8,
        din9 => p_read9,
        din10 => p_read10,
        din11 => p_read11,
        din12 => p_read12,
        din13 => p_read13,
        din14 => p_read14,
        din15 => p_read15,
        din16 => p_read16,
        din17 => p_read17,
        din18 => p_read18,
        din19 => p_read19,
        din20 => p_read20,
        din21 => p_read21,
        din22 => p_read22,
        din23 => p_read23,
        din24 => p_read24,
        din25 => j_fu_240,
        dout => tmp_1_fu_1103_p27);

    mul_6s_6s_12_1_1_U7 : component polarFir_mul_6s_6s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 12)
    port map (
        din0 => ret_V_6_fu_1142_p0,
        din1 => ret_V_6_fu_1142_p1,
        dout => ret_V_6_fu_1142_p2);

    mux_255_6_1_1_U8 : component polarFir_mux_255_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 6,
        din13_WIDTH => 6,
        din14_WIDTH => 6,
        din15_WIDTH => 6,
        din16_WIDTH => 6,
        din17_WIDTH => 6,
        din18_WIDTH => 6,
        din19_WIDTH => 6,
        din20_WIDTH => 6,
        din21_WIDTH => 6,
        din22_WIDTH => 6,
        din23_WIDTH => 6,
        din24_WIDTH => 6,
        din25_WIDTH => 5,
        dout_WIDTH => 6)
    port map (
        din0 => inputImg,
        din1 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813,
        din2 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803,
        din3 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793,
        din4 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783,
        din5 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773,
        din6 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763,
        din7 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753,
        din8 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743,
        din9 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733,
        din10 => computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723,
        din11 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713,
        din12 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703,
        din13 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693,
        din14 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683,
        din15 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673,
        din16 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663,
        din17 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653,
        din18 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643,
        din19 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633,
        din20 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623,
        din21 => p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613,
        din22 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603,
        din23 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593,
        din24 => computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583,
        din25 => j_fu_240,
        dout => tmp_2_fu_1148_p27);

    mux_255_6_1_1_U9 : component polarFir_mux_255_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 6,
        din13_WIDTH => 6,
        din14_WIDTH => 6,
        din15_WIDTH => 6,
        din16_WIDTH => 6,
        din17_WIDTH => 6,
        din18_WIDTH => 6,
        din19_WIDTH => 6,
        din20_WIDTH => 6,
        din21_WIDTH => 6,
        din22_WIDTH => 6,
        din23_WIDTH => 6,
        din24_WIDTH => 6,
        din25_WIDTH => 5,
        dout_WIDTH => 6)
    port map (
        din0 => p_read25,
        din1 => p_read26,
        din2 => p_read27,
        din3 => p_read28,
        din4 => p_read29,
        din5 => p_read30,
        din6 => p_read31,
        din7 => p_read32,
        din8 => p_read33,
        din9 => p_read34,
        din10 => p_read35,
        din11 => p_read36,
        din12 => p_read37,
        din13 => p_read38,
        din14 => p_read39,
        din15 => p_read40,
        din16 => p_read41,
        din17 => p_read42,
        din18 => p_read43,
        din19 => p_read44,
        din20 => p_read45,
        din21 => p_read46,
        din22 => p_read47,
        din23 => p_read48,
        din24 => p_read49,
        din25 => j_fu_240,
        dout => tmp_3_fu_1179_p27);

    mul_6s_6s_12_1_1_U10 : component polarFir_mul_6s_6s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        dout_WIDTH => 12)
    port map (
        din0 => ret_V_8_fu_1218_p0,
        din1 => ret_V_8_fu_1218_p1,
        dout => ret_V_8_fu_1218_p2);

    mac_mulsub_6s_6s_12s_12_4_1_U11 : component polarFir_mac_mulsub_6s_6s_12s_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 12,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1280_p0,
        din1 => grp_fu_1280_p1,
        din2 => ret_V_6_reg_1826_pp0_iter1_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_1280_p3);

    mac_muladd_6s_6s_12s_13_4_1_U12 : component polarFir_mac_muladd_6s_6s_12s_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 12,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1288_p0,
        din1 => grp_fu_1288_p1,
        din2 => ret_V_8_reg_1842_pp0_iter1_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_1288_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    j_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_fu_240 <= ap_const_lv5_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln140_fu_1060_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_240 <= add_ln140_fu_1066_p2;
            end if; 
        end if;
    end process;

    resultImg_V_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                resultImg_V_fu_236 <= ap_const_lv17_0;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                resultImg_V_fu_236 <= resultImg_V_1_fu_1244_p2;
            end if; 
        end if;
    end process;

    resultReal_V_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                resultReal_V_fu_232 <= ap_const_lv17_0;
            elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                resultReal_V_fu_232 <= resultReal_V_1_fu_1235_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_43_reg_1593 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_45_reg_1603 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_46_reg_1673 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_48_reg_1683 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_50_reg_1693 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_52_reg_1703 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineImg_reg_1583 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_42_reg_1588 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_44_reg_1598 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_47_reg_1678 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_49_reg_1688 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_51_reg_1698 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11;
                computeComplexFIR_ap_int_6_ap_int_6_ap_int_6_ap_int_6_ap_int_18_ap_int_18_delayLineReal_reg_1578 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1_l_reg_1733 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2_l_reg_1743 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3_l_reg_1753 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4_l_reg_1763 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5_l_reg_1773 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6_l_reg_1783 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7_l_reg_1793 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8_l_reg_1803 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9_l_reg_1813 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_loa_reg_1723 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_lo_reg_1718 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1_reg_1728 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2_reg_1738 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3_reg_1748 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4_reg_1758 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5_reg_1768 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6_reg_1778 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7_reg_1788 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8_reg_1798 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8;
                computeComplexFIR_mulmulmulmulap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9_reg_1808 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10_loa_reg_1713 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15_loa_reg_1663 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16_loa_reg_1653 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17_loa_reg_1643 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18_loa_reg_1633 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19_loa_reg_1623 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20_loa_reg_1613 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10_lo_reg_1708 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14_lo_reg_1668 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15_lo_reg_1658 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16_lo_reg_1648 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17_lo_reg_1638 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18_lo_reg_1628 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19_lo_reg_1618 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20_lo_reg_1608 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_1 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_2 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_3 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_4 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_5 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_6 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_7 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_8 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg_9 <= inputImg;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_1 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_2 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_3 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_4 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_5 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_6 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_7 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_8 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9;
                computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal_9 <= inputReal;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineImg;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_10;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_11;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_12;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_13;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_14;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_15;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_16;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_17;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_18;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_19;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_20;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_21;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_23 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E12delayLineImg_22;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10 <= computeComplexFIR_ap_int_ap_int_ap_int_ap_int_ap_int_ap_int_delayLineReal;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_10;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_11;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_12;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_13;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_14;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_15;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_16;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_17;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_18;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_19;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_20;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_21;
                p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_23 <= p_ZZ17computeComplexFIR6ap_intILi6EES0_PS0_S1_PS_ILi18EES3_E13delayLineReal_22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln140_fu_1060_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ret_V_6_reg_1826 <= ret_V_6_fu_1142_p2;
                ret_V_8_reg_1842 <= ret_V_8_fu_1218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ret_V_6_reg_1826_pp0_iter1_reg <= ret_V_6_reg_1826;
                ret_V_8_reg_1842_pp0_iter1_reg <= ret_V_8_reg_1842;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln140_fu_1060_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln140_fu_1060_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln140_fu_1060_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln140_fu_1066_p2 <= std_logic_vector(unsigned(j_fu_240) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln140_fu_1060_p2)
    begin
        if ((icmp_ln140_fu_1060_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sext_ln140_fu_1260_p1;
    ap_return_1 <= sext_ln140_1_fu_1264_p1;
    grp_fu_1280_p0 <= sext_ln1494_3_fu_1214_p1(6 - 1 downto 0);
    grp_fu_1280_p1 <= sext_ln1494_2_fu_1210_p1(6 - 1 downto 0);
    grp_fu_1288_p0 <= sext_ln1494_2_fu_1210_p1(6 - 1 downto 0);
    grp_fu_1288_p1 <= sext_ln1494_1_fu_1138_p1(6 - 1 downto 0);
    icmp_ln140_fu_1060_p2 <= "1" when (j_fu_240 = ap_const_lv5_19) else "0";
    resultImg_V_1_fu_1244_p2 <= std_logic_vector(signed(sext_ln840_1_fu_1241_p1) + signed(resultImg_V_fu_236));
    resultReal_V_1_fu_1235_p2 <= std_logic_vector(signed(sext_ln840_fu_1232_p1) + signed(resultReal_V_fu_232));
    ret_V_6_fu_1142_p0 <= sext_ln1494_1_fu_1138_p1(6 - 1 downto 0);
    ret_V_6_fu_1142_p1 <= sext_ln1494_fu_1134_p1(6 - 1 downto 0);
    ret_V_8_fu_1218_p0 <= sext_ln1494_3_fu_1214_p1(6 - 1 downto 0);
    ret_V_8_fu_1218_p1 <= sext_ln1494_fu_1134_p1(6 - 1 downto 0);
        sext_ln140_1_fu_1264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(resultImg_V_fu_236),18));

        sext_ln140_fu_1260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(resultReal_V_fu_232),18));

        sext_ln1494_1_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_1103_p27),12));

        sext_ln1494_2_fu_1210_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_1148_p27),12));

        sext_ln1494_3_fu_1214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_1179_p27),12));

        sext_ln1494_fu_1134_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_1072_p27),12));

        sext_ln840_1_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_1288_p3),17));

        sext_ln840_fu_1232_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_1280_p3),17));

end behav;
