
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpolarfir.h"

/*
* The configuration table for devices
*/

XPolarfir_Config XPolarfir_ConfigTable[XPAR_XPOLARFIR_NUM_INSTANCES] =
{
	{
		XPAR_POLARFIR_0_DEVICE_ID,
		XPAR_POLARFIR_0_S_AXI_CONTROL_BASEADDR
	}
};


